name       : kquickimageeditor
version    : 0.2.0
release    : 2
source     :
    - https://cdn.download.kde.org/stable/kquickimageeditor/kquickimageeditor-0.2.0.tar.xz : 3cfba775498e031f6963669ee0e4426d4fddd48a244b9583620de4d312ba92ca
license    :
    - BSD2-Clause
    - CC0-1.0
    - LGPL-2.1-or-later
component  : programming.library
summary    : KQuickImageEditor is a set of QtQuick components providing basic image editing capabilities.
description: |
    KQuickImageEditor is a set of QtQuick components providing basic image editing capabilities.
builddeps  :
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
