name       : kquickimageeditor
version    : 0.1.3
release    : 1
source     :
    - https://download.kde.org/stable/kquickimageeditor/0.1/kquickimageeditor-0.1.3.tar.xz : 5b13f8e53bc7ea960b24064948f3d28bfb39f47529d5fa63a2090a047465c1ea
license    :
    - BSD2-Clause
    - CC0-1.0
    - LGPL-2.1-or-later
component  : programming.library
summary    : KQuickImageEditor is a set of QtQuick components providing basic image editing capabilities.
description: |
    KQuickImageEditor is a set of QtQuick components providing basic image editing capabilities.
builddeps  :
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
